### ISSUE TITLE
Add quick explanation to the displayed data in Query Monitor.

### ISSUE THREAD

**Issue by NielsdeBlaauw** [NielsdeBlaauw/query-monitor-twig-profile#24]
It might not be trivial to understand what the output is showing.

![screenshot-1](https://user-images.githubusercontent.com/661876/94989902-3fd3ed80-0578-11eb-83d3-e798540c851b.png)

In this screen we can add a short explanation of what everything means, and the first steps to speed up the website.

Think of explaining what the different colors mean (red = >20% execution time, blocks and templates have different colors, etc). And maybe describe some common causes for slowdowns (external API requests, uncached database queries, etc.)

**Comment by Colir** [comment]
+1

**Comment by NielsdeBlaauw** [comment]
Documentation is now available on https://actd.nl/query-monitor-twig-profile/
