### ISSUE TITLE
Add 'history' view.

### ISSUE THREAD

**Issue by NielsdeBlaauw** [NielsdeBlaauw/query-monitor-twig-profile#25]
Maybe we can save the most recent profile information into the WordPress database, or the local storage of the user. This way we can show how the profile rendering has changed over time. Kind of like saving 'snapshots' of the profile from multiple iterations..

**Comment by johnbillion** [comment]
This is something I'm planning on adding to QM, but I've also been saying that for years. In practice it's blocked by the switch to client side rendering otherwise there's no easy way to switch out the data for the view. https://github.com/johnbillion/query-monitor/pull/483
