### ISSUE TITLE
Update wpackagist version

### ISSUE THREAD

**Issue by kamilgrzegorczyk** [NielsdeBlaauw/query-monitor-twig-profile#28]
hey!

It seems that the recent 1.2.0 version was not picked up by wpackagist and the newest one is 1.1.0.
https://wpackagist.org/search?q=query-monitor-twig-profile&type=any&search=

Is there anything you can do to make sure the new version is populated everywhere? Thank you!

**Comment by NielsdeBlaauw** [comment]
Hey @kamilgrzegorczyk 

Thanks for letting me know. I'm seeing the latest 1.2.0 version in wpackagist.

![Screenshot from 2020-11-06 14-42-05](https://user-images.githubusercontent.com/661876/98372602-515c5980-203e-11eb-8af9-457780d09afb.png)


So I think it should be available now. If you are still having issues let me know. You can also download it from packagist.org. It's the same release. See https://packagist.org/packages/nielsdeblaauw/query-monitor-twig-profile

**Comment by kamilgrzegorczyk** [comment]
Hey, yes that works, thank you
